#!/bin/sh

SSID="$wpa_cli -i wlp0s20u3 scan && wpa_cli -i wlp0s20u3 scan_results | fzf | awk '{print $NF}' | tail -1"
read -p 'WPA key (or "NONE"): ' KEY

# Can't indent the cat paragraph
if [ $KEY != "NONE" ]
        then sudo cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
ssid="$SSID"
psk="$KEY"
key_mgmt=WPA-PSK
}
EOF

else sudo cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
ssid="$SSID"
key_mgmt=NONE
}
EOF

fi

sudo sv restart dhcpcd

exit
