#!/bin/sh 

Seleccionar=$(echo "Portapapeles\nGuardar\ncancel" | dmenu -l 3 -p "Screenshot") 
case $Seleccionar in 
	"Portapapeles") 
		scrot -s /tmp/'select-%F_%T.png' -e 'xclip -selection c -t image/png < $f'
		;; 
	"Guardar") 
		scrot -s -d 2 -q 100 'Select_%F_%H%M%S_$wx$h.png' -e 'mv $f /home/skynet/Datos/Capturas/select'; sleep 1; exec notify-send -t 5000 --icon=/home/skynet/.icons/workspace.png 'Área seleccionda' 'guardada en: ~/Datos/Capturas/select'
		;;
	*) ;; 
esac
