#!/bin/sh
# Reiniciar DWM sin cerrar sesión o cerrar aplicaciones
while true;
do
	# Log stderror al fichero
	dwm 2> ~/.dwm.log
done


#csum=""
#new_csum=$(sha1sum $(which dwm))
#while true
#do
#	if [ "$csum" != "$new_csum" ]
#	then
#		csum=$new_csum
#		dwm 2> ~/.dwm.log
#	else
#		exit 0
#	fi
#	new_csum=$(sha1sum $(which dwm))
#	sleep 0.5
#done
