#!/bin/sh

lista=$(xbps-install -nuM | awk '{print $1}' )
lista2=$(xbps-install -nuM | awk '{print $1}' | tail -n 10 )
updates=$(xbps-install -nuM | wc -l)

if [ "$updates" -eq 1 ]; then
	notify-send -i "$HOME/.icons/status/package-upgrade.png" "Hay una actualización disponible:" "$lista"
	echo "$updates"
elif [ "$updates" -le 5 ] && [ "$updates" -gt 1 ]; then
	notify-send -i "$HOME/.icons/status/package-upgrade.png" "Hay $updates actualizaciones disponibles:" "$lista"
	echo "$updates"
elif [ "$updates" -gt 5 ]; then 
	notify-send -i "$HOME/.icons/status/package-upgrade.png" "Hay $updates actualizaciones disponibles:" "$lista2 \n..."
	echo "$updates"
else
	echo ""
fi

sleep 180;
if [ -n "$updates" ] && [ "$updates" -lt 1 ]; then
	echo ""
else
	echo "$updates"
fi

